spring:
  application:
    name: prometheus-rest
  profiles:
    active: dev
  config:
    import: optional:configserver:https://prometheus-config.herokuapp.com/
  #  datasource:
  #    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  kafka:
    properties:
      schema.registry.url: http://127.0.0.1:8081
    bootstrap-servers:
      - 192.168.1.3:9092
    consumer:
      group-id: prometheus
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#      hibernate:
#        dialect: org.hibernate.dialect.Oracle9iDialect
#  cloud:
#    config:
#      uri: https://prometheus-config.herokuapp.com
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /
#logging:
#  level:
#    org:
#      springframework:
#        boot:
#          autoconfigure: debug
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true

